server:
  port: 8081

spring:
  application:
    name: currency-converter
  datasource:
    username: user
    password: admin
    url: jdbc:hsqldb:mem:test
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
  jpa:
    hibernate:
      ddl-auto: create